package ec.edu.ups.EVANeiraPedroCLI.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:52:04.721-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://services.EVANeiraPedroSRV.ups.edu.ec/", name = "AutomovilServicesSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface AutomovilServicesSOAP {

    @WebMethod
    @RequestWrapper(localName = "crearAuto", targetNamespace = "http://services.EVANeiraPedroSRV.ups.edu.ec/", className = "ec.edu.ups.EVANeiraPedroCLI.services.CrearAuto")
    @ResponseWrapper(localName = "crearAutoResponse", targetNamespace = "http://services.EVANeiraPedroSRV.ups.edu.ec/", className = "ec.edu.ups.EVANeiraPedroCLI.services.CrearAutoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearAuto(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.EVANeiraPedroCLI.services.Automovil arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listarAutos", targetNamespace = "http://services.EVANeiraPedroSRV.ups.edu.ec/", className = "ec.edu.ups.EVANeiraPedroCLI.services.ListarAutos")
    @ResponseWrapper(localName = "listarAutosResponse", targetNamespace = "http://services.EVANeiraPedroSRV.ups.edu.ec/", className = "ec.edu.ups.EVANeiraPedroCLI.services.ListarAutosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.EVANeiraPedroCLI.services.Automovil> listarAutos()
;
}
