package ec.edu.ups.EVANeiraPedroCLI.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:52:04.728-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "AutomovilServicesSOAPService",
                  wsdlLocation = "http://localhost:8080/EVANeiraPedroSRV/AutomovilServicesSOAP?wsdl",
                  targetNamespace = "http://services.EVANeiraPedroSRV.ups.edu.ec/")
public class AutomovilServicesSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.EVANeiraPedroSRV.ups.edu.ec/", "AutomovilServicesSOAPService");
    public final static QName AutomovilServicesSOAPPort = new QName("http://services.EVANeiraPedroSRV.ups.edu.ec/", "AutomovilServicesSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EVANeiraPedroSRV/AutomovilServicesSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutomovilServicesSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EVANeiraPedroSRV/AutomovilServicesSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutomovilServicesSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutomovilServicesSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomovilServicesSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AutomovilServicesSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutomovilServicesSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutomovilServicesSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AutomovilServicesSOAP
     */
    @WebEndpoint(name = "AutomovilServicesSOAPPort")
    public AutomovilServicesSOAP getAutomovilServicesSOAPPort() {
        return super.getPort(AutomovilServicesSOAPPort, AutomovilServicesSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomovilServicesSOAP
     */
    @WebEndpoint(name = "AutomovilServicesSOAPPort")
    public AutomovilServicesSOAP getAutomovilServicesSOAPPort(WebServiceFeature... features) {
        return super.getPort(AutomovilServicesSOAPPort, AutomovilServicesSOAP.class, features);
    }

}
