
package ec.edu.ups.EVANeiraPedroCLI.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0 2022-02-01T11:52:04.635-05:00
 * Generated source version: 3.5.0
 *
 */
public final class AutomovilServicesSOAP_AutomovilServicesSOAPPort_Client {

	private static final QName SERVICE_NAME = new QName("http://services.EVANeiraPedroSRV.ups.edu.ec/",
			"AutomovilServicesSOAPService");

	private AutomovilServicesSOAP_AutomovilServicesSOAPPort_Client() {
	}

	AutomovilServicesSOAP port;
	
	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = AutomovilServicesSOAPService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		AutomovilServicesSOAPService ss = new AutomovilServicesSOAPService(wsdlURL, SERVICE_NAME);
		AutomovilServicesSOAP port = ss.getAutomovilServicesSOAPPort();

//		{
//			System.out.println("Invoking crearAuto...");
//			ec.edu.ups.EVANeiraPedroCLI.services.Automovil _crearAuto_arg0 = null;
//			java.lang.String _crearAuto__return = port.crearAuto(_crearAuto_arg0);
//			System.out.println("crearAuto.result=" + _crearAuto__return);
//
//		}
//		{
//			System.out.println("Invoking listarAutos...");
//			java.util.List<ec.edu.ups.EVANeiraPedroCLI.services.Automovil> _listarAutos__return = port.listarAutos();
//			System.out.println("listarAutos.result=" + _listarAutos__return);
//
//		}
	}

}
